### PR TITLE
Updated grid_royale/base.py

### PR DESCRIPTION
**Pull request by dhhruv**
Made some changes in grid_royale/base.py for better understanding.

### CODE REVIEW

**Comment by cool-RR** [comment]
Good, but please fix the indentation. Delete 4 spaces so it's on the same indentation level as the class.

**Comment by dhhruv** [comment]
Done. Intendation fixed.

**Comment by cool-RR** [comment]
Haha, now you removed too many spaces. It should have exactly 4 spaces.

**Comment by dhhruv** [comment]
Yeah, my bad. Completed now.

**Comment by dhhruv** [comment]
Please Check.

**Comment by cool-RR** [comment]
Good job! Thank you.

**Comment by dhhruv** [comment]
Heyy, if there are any other pull requests but related to code then let me
know.

**Comment by cool-RR** [comment]
Okay, here's a more difficult task. I started writing tests in `test_gamey/test_gamey.py`. Make a test on the Blackjack example (`grid_royale/gamey/sample_games/blackjack.py`) that creates a `BlackjackState` object with certain cards, gets the next state from it and does a few sanity check on that new state, like checking that it has all the cards that the last state had and more.

**Comment by dhhruv** [comment]
Cool. I'll work on that.

**Comment by dhhruv** [comment]
But no new files are generated !!! I mean no objects are created.. What to
do ??

**Comment by cool-RR** [comment]
I don't understand what you're saying.

**Comment by dhhruv** [comment]
I ran test_gamey.py as well as blackjack.py but no new cards/objects are
generated and it says there's nothing to commit when I try to commit after
running these files.

**Comment by cool-RR** [comment]
Why would you expect that any changes to files will be made as a result of running these files?

**Comment by dhhruv** [comment]
Then after running those files what to commit !!???

**Comment by cool-RR** [comment]
First, run the tests to make sure they work. Do it by running `pytest` in the repo root. Then add another test function to that file that makes an error, like `1/0`. Run the tests again, and confirm that they now fail. Now, replace the `1/0` code with code that creates a new `BlackjackState` object, then continue from there.

**Comment by dhhruv** [comment]
Okay I'll see what I can do..

**Comment by dhhruv** [comment]
I can't get what you're trying to say. Can you please elaborate it a bit ??

**Comment by cool-RR** [comment]
Did you ever write a test before? Can you show me?

**Comment by dhhruv** [comment]
Actually I didn't. I mean I haven't tried..😅😅

**Comment by cool-RR** [comment]
Ah, sorry, it's really beginner stuff and I can't give you a programming course. Maybe you can learn some by reading the pytest website: https://docs.pytest.org/en/stable/ But really there's a lot of learning and I can't help you.

**Comment by dhhruv** [comment]
It's okay, I'll see what I can do and thanks though for helping me out.

**Pull request merged**
